// swift-tools-version:5.3

// This file was autogenerated, do not modify

import PackageDescription

let package = Package(
    name: "CardScan",
    platforms: [
        .iOS(.v11)
    ],
    products: [
        .library(
            name: "CardScan",
            targets: ["CardScan"]
        ),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(
            name: "CardScan",
            url: "https://downloads.getbouncer.com/swift_package_manager/2.0.0000-beta3/CardScan.xcframework.zip",
            checksum: "6270b6091624ebd2add68aa5f0141fd50ee68383ba9d38edcc1e5d624024de7c"
        )
    ]
)