// swift-tools-version:5.3

// This file was autogenerated, do not modify

import PackageDescription

let package = Package(
    name: "CardScan",
    platforms: [
        .iOS(.v11)
    ],
    products: [
        .library(
            name: "CardScan",
            targets: ["CardScan"]
        ),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(
            name: "CardScan",
            url: "https://downloads.getbouncer.com/swift_package_manager/production-20201218-1608303282/CardScan.xcframework.zip",
            checksum: "1d667ca20ea8b58699a9fde452d5a5ed1b9a516fbb1dae5caa31d81cbe68ecb1"
        )
    ]
)