// swift-tools-version:5.3

// This file was autogenerated, do not modify

import PackageDescription

let package = Package(
    name: "CardScan",
    platforms: [
        .iOS(.v11)
    ],
    products: [
        .library(
            name: "CardScan",
            targets: ["CardScan"]
        ),
    ],
    dependencies: [],
    targets: [
        .binaryTarget(
            name: "CardScan",
            url: "https://downloads.getbouncer.com/swift_package_manager/2.0.4/CardScan.xcframework.zip",
            checksum: "28ea4b71dcc143a1e73983779ade8d814eb52c4eddd7d204b42db8a68e21538d"
        )
    ]
)