// Generated by Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
#ifndef CARDSCAN_SWIFT_H
#define CARDSCAN_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreGraphics;
@import CoreMedia;
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CardScan",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class NSCoder;

SWIFT_CLASS("_TtC8CardScan8BlurView")
@interface BlurView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

SWIFT_PROTOCOL("_TtP8CardScan21CaptureOutputDelegate_") SWIFT_AVAILABILITY(ios,introduced=11.2)
@protocol CaptureOutputDelegate
- (void)capture:(AVCaptureOutput * _Nonnull)output didOutput:(CMSampleBufferRef _Nonnull)sampleBuffer from:(AVCaptureConnection * _Nonnull)connection;
@end

typedef SWIFT_ENUM(NSInteger, CardNetwork, open) {
  CardNetworkVISA = 0,
  CardNetworkMASTERCARD = 1,
  CardNetworkAMEX = 2,
  CardNetworkDISCOVER = 3,
  CardNetworkUNIONPAY = 4,
  CardNetworkJCB = 5,
  CardNetworkDINERSCLUB = 6,
  CardNetworkREGIONAL = 7,
  CardNetworkUNKNOWN = 8,
};

typedef SWIFT_ENUM(NSInteger, CardType, open) {
  CardTypeCREDIT = 0,
  CardTypeDEBIT = 1,
  CardTypePREPAID = 2,
  CardTypeUNKNOWN = 3,
};


SWIFT_CLASS("_TtC8CardScan10CornerView")
@interface CornerView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
@end

@class UIImage;

SWIFT_CLASS("_TtC8CardScan10CreditCard")
@interface CreditCard : NSObject
@property (nonatomic, copy) NSString * _Nonnull number;
@property (nonatomic, copy) NSString * _Nullable expiryMonth;
@property (nonatomic, copy) NSString * _Nullable expiryYear;
@property (nonatomic, copy) NSString * _Nullable name;
@property (nonatomic, strong) UIImage * _Nullable image;
@property (nonatomic, copy) NSString * _Nullable cvv;
@property (nonatomic, copy) NSString * _Nullable postalCode;
- (NSString * _Nullable)expiryForDisplay SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_PROTOCOL("_TtP8CardScan21ScanStringsDataSource_") SWIFT_AVAILABILITY(ios,introduced=11.2)
@protocol ScanStringsDataSource
- (NSString * _Nonnull)scanCard SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)positionCard SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)backButton SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)skipButton SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_PROTOCOL("_TtP8CardScan25FullScanStringsDataSource_") SWIFT_AVAILABILITY(ios,introduced=11.2)
@protocol FullScanStringsDataSource <ScanStringsDataSource>
- (NSString * _Nonnull)denyPermissionTitle SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)denyPermissionMessage SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)denyPermissionButton SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC8CardScan31OcrAccurateMainLoopStateMachine")
@interface OcrAccurateMainLoopStateMachine : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC8CardScan23OcrMainLoopStateMachine")
@interface OcrMainLoopStateMachine : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CardScan11PreviewView")
@interface PreviewView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder SWIFT_UNAVAILABLE;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) Class _Nonnull layerClass;)
+ (Class _Nonnull)layerClass SWIFT_WARN_UNUSED_RESULT;
- (void)layoutSubviews;
@end

@class ScanConfiguration;
@protocol UIViewControllerTransitionCoordinator;
@class NSBundle;

SWIFT_CLASS("_TtC8CardScan22ScanBaseViewController") SWIFT_AVAILABILITY(ios,introduced=11.2)
@interface ScanBaseViewController : UIViewController <AVCaptureVideoDataOutputSampleBufferDelegate>
@property (nonatomic) BOOL includeCardImage;
@property (nonatomic) BOOL showDebugImageView;
@property (nonatomic) BOOL sendScanStats;
- (void)onScannedCardWithNumber:(NSString * _Nonnull)number expiryYear:(NSString * _Nullable)expiryYear expiryMonth:(NSString * _Nullable)expiryMonth scannedImage:(UIImage * _Nullable)scannedImage;
- (void)showCardNumber:(NSString * _Nonnull)number expiry:(NSString * _Nullable)expiry;
- (void)showWrongCardWithNumber:(NSString * _Nullable)number expiry:(NSString * _Nullable)expiry name:(NSString * _Nullable)name;
- (void)showNoCard;
- (void)onCameraPermissionDeniedWithShowedPrompt:(BOOL)showedPrompt;
- (BOOL)useCurrentFrameNumberWithErrorCorrectedNumber:(NSString * _Nullable)errorCorrectedNumber currentFrameNumber:(NSString * _Nonnull)currentFrameNumber SWIFT_WARN_UNUSED_RESULT;
+ (void)configureWithApiKey:(NSString * _Nullable)apiKey;
+ (UIInterfaceOrientationMask)supportedOrientationMaskOrDefault SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isCompatible SWIFT_WARN_UNUSED_RESULT;
+ (BOOL)isCompatibleWithConfiguration:(ScanConfiguration * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
+ (UIImage * _Nullable)cameraImage SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
@property (nonatomic, readonly) UIStatusBarStyle preferredStatusBarStyle;
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id <UIViewControllerTransitionCoordinator> _Nonnull)coordinator;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)viewWillDisappear:(BOOL)animated;
- (void)viewDidDisappear:(BOOL)animated;
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8CardScan17ScanConfiguration")
@interface ScanConfiguration : NSObject
@property (nonatomic) BOOL runOnOldDevices;
@property (nonatomic) BOOL setPreviouslyDeniedDevicesAsIncompatible;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class ScanViewController;

SWIFT_PROTOCOL("_TtP8CardScan12ScanDelegate_") SWIFT_AVAILABILITY(ios,introduced=11.2)
@protocol ScanDelegate
- (void)userDidCancel:(ScanViewController * _Nonnull)scanViewController;
- (void)userDidScanCard:(ScanViewController * _Nonnull)scanViewController creditCard:(CreditCard * _Nonnull)creditCard;
@optional
- (void)userDidScanQrCode:(ScanViewController * _Nonnull)scanViewController payload:(NSString * _Nonnull)payload;
@required
- (void)userDidSkip:(ScanViewController * _Nonnull)scanViewController;
@end

typedef SWIFT_ENUM(NSInteger, ScanPerformance, open) {
  ScanPerformanceFast = 0,
  ScanPerformanceAccurate = 1,
};


@class UIColor;
@class UIFont;
@class NSNumber;
@class UILabel;

SWIFT_CLASS("_TtC8CardScan18ScanViewController") SWIFT_AVAILABILITY(ios,introduced=11.2)
@interface ScanViewController : ScanBaseViewController
@property (nonatomic, weak) id <ScanStringsDataSource> _Nullable stringDataSource;
@property (nonatomic) BOOL allowSkip;
@property (nonatomic) BOOL hideBackButtonImage;
@property (nonatomic, strong) UIImage * _Nullable backButtonImage;
@property (nonatomic, strong) UIColor * _Nullable backButtonColor;
@property (nonatomic, strong) UIFont * _Nullable backButtonFont;
@property (nonatomic, strong) UIFont * _Nullable scanCardFont;
@property (nonatomic, strong) UIFont * _Nullable positionCardFont;
@property (nonatomic, strong) UIFont * _Nullable skipButtonFont;
@property (nonatomic, strong) NSNumber * _Nullable backButtonImageToTextDelta;
@property (nonatomic, strong) UIImage * _Nullable torchButtonImage;
@property (nonatomic, strong) UIColor * _Nullable cornerColor;
@property (nonatomic, weak) IBOutlet UILabel * _Null_unspecified regionOfInterestLabel;
+ (ScanViewController * _Nullable)createViewControllerWithDelegate:(id <ScanDelegate> _Nullable)delegate SWIFT_WARN_UNUSED_RESULT;
+ (ScanViewController * _Nullable)createViewControllerWithDelegate:(id <ScanDelegate> _Nullable)delegate configuration:(ScanConfiguration * _Nonnull)configuration SWIFT_WARN_UNUSED_RESULT;
- (void)cancelWithCallDelegate:(BOOL)callDelegate;
- (void)onCameraPermissionDeniedWithShowedPrompt:(BOOL)showedPrompt;
- (void)viewDidLoad;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidLayoutSubviews;
- (void)showCardNumber:(NSString * _Nonnull)number expiry:(NSString * _Nullable)expiry;
- (BOOL)useCurrentFrameNumberWithErrorCorrectedNumber:(NSString * _Nullable)errorCorrectedNumber currentFrameNumber:(NSString * _Nonnull)currentFrameNumber SWIFT_WARN_UNUSED_RESULT;
- (void)captureOutput:(AVCaptureOutput * _Nonnull)output didOutputSampleBuffer:(CMSampleBufferRef _Nonnull)sampleBuffer fromConnection:(AVCaptureConnection * _Nonnull)connection;
- (void)onScannedCardWithNumber:(NSString * _Nonnull)number expiryYear:(NSString * _Nullable)expiryYear expiryMonth:(NSString * _Nullable)expiryMonth scannedImage:(UIImage * _Nullable)scannedImage;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end


@class SimpleScanViewController;

SWIFT_PROTOCOL("_TtP8CardScan18SimpleScanDelegate_") SWIFT_AVAILABILITY(ios,introduced=11.2)
@protocol SimpleScanDelegate
- (void)userDidCancelSimple:(SimpleScanViewController * _Nonnull)scanViewController;
- (void)userDidScanCardSimple:(SimpleScanViewController * _Nonnull)scanViewController creditCard:(CreditCard * _Nonnull)creditCard;
@end

@class UIButton;

SWIFT_CLASS("_TtC8CardScan24SimpleScanViewController") SWIFT_AVAILABILITY(ios,introduced=11.2)
@interface SimpleScanViewController : ScanBaseViewController
@property (nonatomic, strong) UIButton * _Nonnull closeButton;
@property (nonatomic, strong) UIButton * _Nonnull torchButton;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull descriptionString;)
+ (NSString * _Nonnull)descriptionString SWIFT_WARN_UNUSED_RESULT;
+ (void)setDescriptionString:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull enableCameraPermissionString;)
+ (NSString * _Nonnull)enableCameraPermissionString SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableCameraPermissionString:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull enableCameraPermissionsDescriptionString;)
+ (NSString * _Nonnull)enableCameraPermissionsDescriptionString SWIFT_WARN_UNUSED_RESULT;
+ (void)setEnableCameraPermissionsDescriptionString:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull closeButtonString;)
+ (NSString * _Nonnull)closeButtonString SWIFT_WARN_UNUSED_RESULT;
+ (void)setCloseButtonString:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull torchButtonString;)
+ (NSString * _Nonnull)torchButtonString SWIFT_WARN_UNUSED_RESULT;
+ (void)setTorchButtonString:(NSString * _Nonnull)value;
@property (nonatomic, weak) id <SimpleScanDelegate> _Nullable delegate;
@property (nonatomic) enum ScanPerformance scanPerformancePriority;
@property (nonatomic) double maxErrorCorrectionDuration;
+ (SimpleScanViewController * _Nonnull)createViewController SWIFT_WARN_UNUSED_RESULT;
- (void)viewDidLoad;
- (void)viewDidDisappear:(BOOL)animated;
- (void)onScannedCardWithNumber:(NSString * _Nonnull)number expiryYear:(NSString * _Nullable)expiryYear expiryMonth:(NSString * _Nullable)expiryMonth scannedImage:(UIImage * _Nullable)scannedImage;
- (void)onCameraPermissionDeniedWithShowedPrompt:(BOOL)showedPrompt;
- (void)cancelButtonPress;
- (void)torchButtonPress;
/// Warning: if the user navigates to settings and updates the setting, it’ll suspend your app.
- (void)enableCameraPermissionsPress;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end









#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif
