from jinja2 import Template
import sys


COMMENT = 'This file was autogenerated, do not modify'


def main():
    if len(sys.argv) != 3:
        print('Usage {}: version checksum < Package.template > Package.swift'.format(sys.argv[0]))
        sys.exit(1)

    values = {'version': sys.argv[1],
              'checksum': sys.argv[2],
              'top_comment': COMMENT}

    template = Template(sys.stdin.read())
    sys.stdout.write(template.render(values))

    
if __name__ == '__main__':
    main()
