name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: test
        run: |
          cd Example
          pod install
          xcodebuild test -workspace CardScan.xcworkspace -scheme CardScan_Example -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.6'

      - name: upload-artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report
          path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult
