name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: unit-test
        run:
          xcodebuild test -workspace CardScan.xcworkspace -scheme CardScanExample -destination 'platform=iOS Simulator,name=iPhone 11'

      - name: upload-artifacts-unit
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report-unit
          path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult

      - name: ui-test
        run:
          touch CardScanSystemTest/CardScanSystemTest/Resources/apikey.json
          xcodebuild test -workspace CardScan.xcworkspace -scheme CardScanSystemTest -destination 'platform=iOS Simulator,name=iPhone 11'

      - name: upload-artifacts-ui
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-report-ui
          path: /Users/runner/Library/Developer/Xcode/DerivedData/*/Logs/Test/*.xcresult

